// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminSolveProblemReducer from "../admin_solve_problem_reducer";
import AnswerQuizReducer from "../answer_quiz_reducer";
import BuyAbilityReducer from "../buy_ability_reducer";
import ClaimFirstAdminReducer from "../claim_first_admin_reducer";
import ClearSabotageEventReducer from "../clear_sabotage_event_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DeleteProblemReducer from "../delete_problem_reducer";
import DeleteQuizQuestionReducer from "../delete_quiz_question_reducer";
import ExpireGameReducer from "../expire_game_reducer";
import ForfeitReducer from "../forfeit_reducer";
import InsertProblemReducer from "../insert_problem_reducer";
import InsertQuizQuestionReducer from "../insert_quiz_question_reducer";
import JoinQueueReducer from "../join_queue_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveQueueReducer from "../leave_queue_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import PromoteToAdminReducer from "../promote_to_admin_reducer";
import SaveDraftReducer from "../save_draft_reducer";
import SeedPowerupsReducer from "../seed_powerups_reducer";
import SeedProblemReducer from "../seed_problem_reducer";
import SeedQuizQuestionsReducer from "../seed_quiz_questions_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetExecutorIdentityReducer from "../set_executor_identity_reducer";
import SetLoadoutPrefReducer from "../set_loadout_pref_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitResultReducer from "../submit_result_reducer";
import UpdateProblemReducer from "../update_problem_reducer";
import UpdateQuizQuestionReducer from "../update_quiz_question_reducer";
import UpdateRoomSettingsReducer from "../update_room_settings_reducer";
import UseAbilityReducer from "../use_ability_reducer";
import UsePowerupReducer from "../use_powerup_reducer";

export type AdminSolveProblemParams = __Infer<typeof AdminSolveProblemReducer>;
export type AnswerQuizParams = __Infer<typeof AnswerQuizReducer>;
export type BuyAbilityParams = __Infer<typeof BuyAbilityReducer>;
export type ClaimFirstAdminParams = __Infer<typeof ClaimFirstAdminReducer>;
export type ClearSabotageEventParams = __Infer<typeof ClearSabotageEventReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeleteProblemParams = __Infer<typeof DeleteProblemReducer>;
export type DeleteQuizQuestionParams = __Infer<typeof DeleteQuizQuestionReducer>;
export type ExpireGameParams = __Infer<typeof ExpireGameReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type InsertProblemParams = __Infer<typeof InsertProblemReducer>;
export type InsertQuizQuestionParams = __Infer<typeof InsertQuizQuestionReducer>;
export type JoinQueueParams = __Infer<typeof JoinQueueReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveQueueParams = __Infer<typeof LeaveQueueReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type PromoteToAdminParams = __Infer<typeof PromoteToAdminReducer>;
export type SaveDraftParams = __Infer<typeof SaveDraftReducer>;
export type SeedPowerupsParams = __Infer<typeof SeedPowerupsReducer>;
export type SeedProblemParams = __Infer<typeof SeedProblemReducer>;
export type SeedQuizQuestionsParams = __Infer<typeof SeedQuizQuestionsReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetExecutorIdentityParams = __Infer<typeof SetExecutorIdentityReducer>;
export type SetLoadoutPrefParams = __Infer<typeof SetLoadoutPrefReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitResultParams = __Infer<typeof SubmitResultReducer>;
export type UpdateProblemParams = __Infer<typeof UpdateProblemReducer>;
export type UpdateQuizQuestionParams = __Infer<typeof UpdateQuizQuestionReducer>;
export type UpdateRoomSettingsParams = __Infer<typeof UpdateRoomSettingsReducer>;
export type UseAbilityParams = __Infer<typeof UseAbilityReducer>;
export type UsePowerupParams = __Infer<typeof UsePowerupReducer>;

