// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomCode: __t.string().name("room_code"),
  player1Identity: __t.identity().name("player_1_identity"),
  player2Identity: __t.identity().name("player_2_identity"),
  player1Hp: __t.i32().name("player_1_hp"),
  player2Hp: __t.i32().name("player_2_hp"),
  player1Sp: __t.i32().name("player_1_sp"),
  player2Sp: __t.i32().name("player_2_sp"),
  player1Mp: __t.i32().name("player_1_mp"),
  player2Mp: __t.i32().name("player_2_mp"),
  player1ProblemIndex: __t.u32().name("player_1_problem_index"),
  player2ProblemIndex: __t.u32().name("player_2_problem_index"),
  player1Abilities: __t.string().name("player_1_abilities"),
  player2Abilities: __t.string().name("player_2_abilities"),
  problemIds: __t.string().name("problem_ids"),
  status: __t.string(),
  startTime: __t.timestamp().name("start_time"),
  winnerIdentity: __t.option(__t.identity()).name("winner_identity"),
});
