// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  roomCode: __t.string().name("room_code"),
  player1Identity: __t.identity().name("player_1_identity"),
  player2Identity: __t.identity().name("player_2_identity"),
  player1Hp: __t.i32().name("player_1_hp"),
  player2Hp: __t.i32().name("player_2_hp"),
  player1Sp: __t.i32().name("player_1_sp"),
  player2Sp: __t.i32().name("player_2_sp"),
  player1Mp: __t.i32().name("player_1_mp"),
  player2Mp: __t.i32().name("player_2_mp"),
  player1SolvedIds: __t.string().name("player_1_solved_ids"),
  player2SolvedIds: __t.string().name("player_2_solved_ids"),
  player1Abilities: __t.string().name("player_1_abilities"),
  player2Abilities: __t.string().name("player_2_abilities"),
  problemIds: __t.string().name("problem_ids"),
  status: __t.string(),
  startTime: __t.timestamp().name("start_time"),
  winnerIdentity: __t.option(__t.identity()).name("winner_identity"),
  player1Currency: __t.u32().name("player_1_currency"),
  player2Currency: __t.u32().name("player_2_currency"),
  player1QuizBonus: __t.u32().name("player_1_quiz_bonus"),
  player2QuizBonus: __t.u32().name("player_2_quiz_bonus"),
  player1LastQuizAt: __t.timestamp().name("player_1_last_quiz_at"),
  player2LastQuizAt: __t.timestamp().name("player_2_last_quiz_at"),
  player1Shield: __t.i32().name("player_1_shield"),
  player2Shield: __t.i32().name("player_2_shield"),
  player1DmgBonus: __t.i32().name("player_1_dmg_bonus"),
  player2DmgBonus: __t.i32().name("player_2_dmg_bonus"),
  player1DmgMultPct: __t.i32().name("player_1_dmg_mult_pct"),
  player2DmgMultPct: __t.i32().name("player_2_dmg_mult_pct"),
});
