// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomCode: __t.string().name("room_code"),
  player1Identity: __t.identity().name("player_1_identity"),
  player2Identity: __t.identity().name("player_2_identity"),
  winnerIdentity: __t.identity().name("winner_identity"),
  problemIds: __t.string().name("problem_ids"),
  problemTitles: __t.string().name("problem_titles"),
  difficulties: __t.string(),
  player1SolveTime: __t.u32().name("player_1_solve_time"),
  player2SolveTime: __t.u32().name("player_2_solve_time"),
  player1Language: __t.string().name("player_1_language"),
  player2Language: __t.string().name("player_2_language"),
  player1Accepted: __t.bool().name("player_1_accepted"),
  player2Accepted: __t.bool().name("player_2_accepted"),
  playedAt: __t.timestamp().name("played_at"),
});
