// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  description: __t.string(),
  difficulty: __t.string(),
  methodName: __t.string().name("method_name"),
  sampleTestCases: __t.string().name("sample_test_cases"),
  sampleTestResults: __t.string().name("sample_test_results"),
  hiddenTestCases: __t.string().name("hidden_test_cases"),
  hiddenTestResults: __t.string().name("hidden_test_results"),
  boilerplatePython: __t.string().name("boilerplate_python"),
  boilerplateJava: __t.string().name("boilerplate_java"),
  boilerplateCpp: __t.string().name("boilerplate_cpp"),
  compareFuncPython: __t.string().name("compare_func_python"),
  compareFuncJava: __t.string().name("compare_func_java"),
  compareFuncCpp: __t.string().name("compare_func_cpp"),
  createdBy: __t.identity().name("created_by"),
  isApproved: __t.bool().name("is_approved"),
});
