// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  hostIdentity: __t.identity().name("host_identity"),
  guestIdentity: __t.option(__t.identity()).name("guest_identity"),
  hostReady: __t.bool().name("host_ready"),
  guestReady: __t.bool().name("guest_ready"),
  status: __t.string(),
  settings: __t.string(),
});
