// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  difficulty: __t.string(),
  methodName: __t.string(),
  sampleTestCases: __t.string(),
  sampleTestResults: __t.string(),
  hiddenTestCases: __t.string(),
  hiddenTestResults: __t.string(),
  boilerplatePython: __t.string(),
  boilerplateJava: __t.string(),
  boilerplateCpp: __t.string(),
  compareFuncPython: __t.string(),
  compareFuncJava: __t.string(),
  compareFuncCpp: __t.string(),
  problemKind: __t.string(),
};
