// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BuyAbilityReducer from "../buy_ability_reducer";
import ClaimFirstAdminReducer from "../claim_first_admin_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DeleteProblemReducer from "../delete_problem_reducer";
import ForfeitReducer from "../forfeit_reducer";
import InsertProblemReducer from "../insert_problem_reducer";
import JoinQueueReducer from "../join_queue_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveQueueReducer from "../leave_queue_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import PromoteToAdminReducer from "../promote_to_admin_reducer";
import SaveDraftReducer from "../save_draft_reducer";
import SeedProblemReducer from "../seed_problem_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetExecutorIdentityReducer from "../set_executor_identity_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitResultReducer from "../submit_result_reducer";
import UpdateProblemReducer from "../update_problem_reducer";
import UpdateRoomSettingsReducer from "../update_room_settings_reducer";
import UseAbilityReducer from "../use_ability_reducer";

export type BuyAbilityParams = __Infer<typeof BuyAbilityReducer>;
export type ClaimFirstAdminParams = __Infer<typeof ClaimFirstAdminReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeleteProblemParams = __Infer<typeof DeleteProblemReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type InsertProblemParams = __Infer<typeof InsertProblemReducer>;
export type JoinQueueParams = __Infer<typeof JoinQueueReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveQueueParams = __Infer<typeof LeaveQueueReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type PromoteToAdminParams = __Infer<typeof PromoteToAdminReducer>;
export type SaveDraftParams = __Infer<typeof SaveDraftReducer>;
export type SeedProblemParams = __Infer<typeof SeedProblemReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetExecutorIdentityParams = __Infer<typeof SetExecutorIdentityReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitResultParams = __Infer<typeof SubmitResultReducer>;
export type UpdateProblemParams = __Infer<typeof UpdateProblemReducer>;
export type UpdateRoomSettingsParams = __Infer<typeof UpdateRoomSettingsReducer>;
export type UseAbilityParams = __Infer<typeof UseAbilityReducer>;

