// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApproveProblemReducer from "../approve_problem_reducer";
import BuyAbilityReducer from "../buy_ability_reducer";
import CreateRoomReducer from "../create_room_reducer";
import ForfeitReducer from "../forfeit_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetExecutorIdentityReducer from "../set_executor_identity_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetReadyReducer from "../set_ready_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitResultReducer from "../submit_result_reducer";
import UseAbilityReducer from "../use_ability_reducer";

export type ApproveProblemParams = __Infer<typeof ApproveProblemReducer>;
export type BuyAbilityParams = __Infer<typeof BuyAbilityReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type ForfeitParams = __Infer<typeof ForfeitReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetExecutorIdentityParams = __Infer<typeof SetExecutorIdentityReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitResultParams = __Infer<typeof SubmitResultReducer>;
export type UseAbilityParams = __Infer<typeof UseAbilityReducer>;

