// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.string().name("game_id"),
  playerIdentity: __t.identity().name("player_identity"),
  problemId: __t.u64().name("problem_id"),
  passed: __t.u32(),
  total: __t.u32(),
  solveTime: __t.u32().name("solve_time"),
  language: __t.string(),
  submittedAt: __t.timestamp().name("submitted_at"),
});
