// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  gameId: __t.string(),
  senderIdentity: __t.identity(),
  text: __t.string(),
  sent: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ExecutorConfig = __t.object("ExecutorConfig", {
  id: __t.u32(),
  executorIdentity: __t.identity(),
});
export type ExecutorConfig = __Infer<typeof ExecutorConfig>;

export const GameState = __t.object("GameState", {
  id: __t.string(),
  roomCode: __t.string(),
  player1Identity: __t.identity(),
  player2Identity: __t.identity(),
  player1Hp: __t.i32(),
  player2Hp: __t.i32(),
  player1Sp: __t.i32(),
  player2Sp: __t.i32(),
  player1Mp: __t.i32(),
  player2Mp: __t.i32(),
  player1ProblemIndex: __t.u32(),
  player2ProblemIndex: __t.u32(),
  player1Abilities: __t.string(),
  player2Abilities: __t.string(),
  problemIds: __t.string(),
  status: __t.string(),
  startTime: __t.timestamp(),
  winnerIdentity: __t.option(__t.identity()),
});
export type GameState = __Infer<typeof GameState>;

export const MatchHistory = __t.object("MatchHistory", {
  id: __t.u64(),
  roomCode: __t.string(),
  player1Identity: __t.identity(),
  player2Identity: __t.identity(),
  winnerIdentity: __t.identity(),
  problemId: __t.u64(),
  problemTitle: __t.string(),
  difficulty: __t.string(),
  player1SolveTime: __t.u32(),
  player2SolveTime: __t.u32(),
  player1Language: __t.string(),
  player2Language: __t.string(),
  player1Accepted: __t.bool(),
  player2Accepted: __t.bool(),
  playedAt: __t.timestamp(),
});
export type MatchHistory = __Infer<typeof MatchHistory>;

export const Problem = __t.object("Problem", {
  id: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  difficulty: __t.string(),
  methodName: __t.string(),
  sampleTestCases: __t.string(),
  sampleTestResults: __t.string(),
  hiddenTestCases: __t.string(),
  hiddenTestResults: __t.string(),
  boilerplatePython: __t.string(),
  boilerplateJava: __t.string(),
  boilerplateCpp: __t.string(),
  compareFuncPython: __t.string(),
  compareFuncJava: __t.string(),
  compareFuncCpp: __t.string(),
  createdBy: __t.identity(),
  isApproved: __t.bool(),
});
export type Problem = __Infer<typeof Problem>;

export const Room = __t.object("Room", {
  code: __t.string(),
  hostIdentity: __t.identity(),
  guestIdentity: __t.option(__t.identity()),
  hostReady: __t.bool(),
  guestReady: __t.bool(),
  status: __t.string(),
  settings: __t.string(),
});
export type Room = __Infer<typeof Room>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  firstName: __t.string(),
  lastName: __t.string(),
  githubId: __t.string(),
  avatarUrl: __t.string(),
  isAdmin: __t.bool(),
  eloRating: __t.i32(),
  totalWins: __t.u32(),
  totalMatches: __t.u32(),
  currentStreak: __t.u32(),
});
export type User = __Infer<typeof User>;

